
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://allan.ensup.eu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ditBonjour", targetNamespace = "http://allan.ensup.eu/", className = "client.DitBonjour")
    @ResponseWrapper(localName = "ditBonjourResponse", targetNamespace = "http://allan.ensup.eu/", className = "client.DitBonjourResponse")
    @Action(input = "http://allan.ensup.eu/Hello/ditBonjourRequest", output = "http://allan.ensup.eu/Hello/ditBonjourResponse")
    public String ditBonjour(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
